// Writes src/lib/icons.ts: path data for the few Material Symbols the app uses (self-hosted subset,
// no icon font download). Edit `names` and run `npm run icons`.
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const names = {
  upload: 'upload_file',
  add: 'add',
  rotateLeft: 'rotate_90_degrees_ccw',
  rotateRight: 'rotate_90_degrees_cw',
  delete: 'delete',
  selectAll: 'select_all',
  deselect: 'deselect',
  undo: 'undo',
  redo: 'redo',
  download: 'download',
  close: 'close',
  check: 'check',
  chevronLeft: 'chevron_left',
  chevronRight: 'chevron_right',
  startOver: 'restart_alt',
  more: 'more_vert',
  code: 'code',
  info: 'info',
  lock: 'lock',
  warning: 'warning',
  zoom: 'zoom_in',
  settings: 'settings',
};

let out = '// Generated by scripts/make-icons.mjs from @material-symbols/svg-400 (outlined, Apache-2.0).\n';
out += '// viewBox for every path: 0 -960 960 960.\nexport const icons = {\n';
for (const [key, file] of Object.entries(names)) {
  const svg = fs.readFileSync(path.join(root, 'node_modules/@material-symbols/svg-400/outlined', `${file}.svg`), 'utf8');
  const d = [...svg.matchAll(/ d="([^"]+)"/g)].map((m) => m[1]).join(' ');
  out += `  ${key}: '${d}',\n`;
}
out += '} as const;\n\nexport type IconName = keyof typeof icons;\n';
fs.writeFileSync(path.join(root, 'src/lib/icons.ts'), out);
console.log(`src/lib/icons.ts: ${Object.keys(names).length} icons`);
